# Generated by Django 5.1 on 2024-08-08 00:48

import django.db.models.deletion
import django.db.models.functions.text
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': '"task_manager_category"',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='myapp_category_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание задачи')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='NEW', max_length=25, verbose_name='статус задачи')),
                ('deadline', models.DateTimeField(default=myapp.models.default_deadline, verbose_name='дата и время дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('categories', models.ManyToManyField(blank=True, related_name='tasks', related_query_name='task', to='myapp.category', verbose_name='категории задачи')),
            ],
            options={
                'verbose_name': 'Task',
                'db_table': '"task_manager_task"',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание задачи')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='NEW', max_length=25, verbose_name='статус задачи')),
                ('deadline', models.DateTimeField(default=myapp.models.default_deadline, verbose_name='дата и время дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', related_query_name='sub_task', to='myapp.task', verbose_name='основная задача')),
            ],
            options={
                'verbose_name': 'SubTask',
                'db_table': '"task_manager_subtask"',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='myapp_task_title_unique'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='myapp_subtask_title_unique'),
        ),
    ]
